title:        DroidBytes
tagline:      'DroidBytes'
description:  'Random thoughts and findings from a professional Android developer'
url:          http://michaelworth.github.io
version:      1.1.1
author:
  name:       'Mike Worth'
  email:      'mike.worth@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
